[2021-02-02T20:46:30Z] DEBUG    - Logging set up successfully
[2021-02-02T20:46:30Z] DEBUG    - Running validate: Namespace(command=<function validate at 0x10bb53ca0>, subparser_name='validate', verbose=0, version=False)
[2021-02-02T20:46:30Z] DEBUG    - Root directory: /Volumes/workplace/uluru/src/AWSCloudFormationResourceProvidersServiceCatalog
[2021-02-02T20:46:30Z] DEBUG    - Loading project file '/Volumes/workplace/uluru/src/AWSCloudFormationResourceProvidersServiceCatalog/.rpdk-config'
[2021-02-02T20:46:30Z] DEBUG    - Project file not found. Have you run 'init'?
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 343, in load
    self.load_settings()
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 166, in load_settings
    with self.settings_path.open("r", encoding="utf-8") as f:
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/workplace/uluru/src/AWSCloudFormationResourceProvidersServiceCatalog/.rpdk-config'
[2021-02-02T20:46:30Z] DEBUG    - Caught exit recommendation
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 343, in load
    self.load_settings()
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 166, in load_settings
    with self.settings_path.open("r", encoding="utf-8") as f:
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1221, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1077, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/workplace/uluru/src/AWSCloudFormationResourceProvidersServiceCatalog/.rpdk-config'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/cli.py", line 100, in main
    args.command(args)
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/validate.py", line 14, in validate
    project.load()
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 345, in load
    self._raise_invalid_project(
  File "/usr/local/lib/python3.8/site-packages/rpdk/core/project.py", line 161, in _raise_invalid_project
    raise InvalidProjectError(msg) from e
rpdk.core.exceptions.InvalidProjectError: Project file not found. Have you run 'init'?
[2021-02-02T20:46:30Z] CRITICAL - Project file not found. Have you run 'init'?
